In [1]:
# pip install numpy
# for installing a library

In [2]:
import numpy as np

In [3]:
li=[23,67,54,89,31]
li

[23, 67, 54, 89, 31]

In [4]:
# array has only one datatype
# vector 1-D
# matrix 2-D
# tensor 3-D

In [6]:
# convert a list to  array
ar=np.array(li)
ar

array([23, 67, 54, 89, 31])

In [7]:
type(ar)

numpy.ndarray

In [8]:
l=[1,2,3,6.4,6.4,'a',True,3+2j]

In [9]:
ar1=np.array(l)
print(ar1)
print(type(ar1))
ar1.dtype

['1' '2' '3' '6.4' '6.4' 'a' 'True' '(3+2j)']
<class 'numpy.ndarray'>


dtype('<U64')

In [10]:
# string>complex_no>float>integer>bool
ar1.dtype

dtype('<U64')

In [13]:
print(ar)
ar1.ndim
# ar.dtype

[23 67 54 89 31]


1

In [19]:
print(ar.shape)
print(len(ar))
ar.size

(5,)
5


5

In [20]:
L=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]

In [21]:
a=np.array(L)

In [22]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [23]:
a.shape

(4, 3)

In [24]:
a.ndim


2

In [26]:
print(a.shape)

print(a.size)
len(a)

(4, 3)
12


4

In [27]:
A=[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]

In [28]:
ar3=np.array(A)

In [29]:
ar3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [35]:
print(len(a))
print(a.size)
ar3.shape


4
12


(2, 2, 3)

In [36]:
print(ar3.ndim)
ar3.strides
# The strides of an array tell us how many bytes we have to skip in memory
# to move to the next position along a certain axis

3


(24, 12, 4)

In [38]:
np.zeros(4,dtype=int,order='F')


array([0, 0, 0, 0])

In [39]:
z1=np.zeros((5,3),dtype=float,order='F')
print(z1)
z1.dtype


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


dtype('float64')

In [40]:
z1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [41]:
z=np.zeros((2,3,2),dtype=int,order='C')
z.dtype
z

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]])

In [42]:
c=np.ones((2,3,4),dtype=str)
c

array([[['1', '1', '1', '1'],
        ['1', '1', '1', '1'],
        ['1', '1', '1', '1']],

       [['1', '1', '1', '1'],
        ['1', '1', '1', '1'],
        ['1', '1', '1', '1']]], dtype='<U1')

In [58]:
# np.full()- to make a matrix with a particular value
np.full((2,4,8),786,dtype=int)

array([[[786, 786, 786, 786, 786, 786, 786, 786],
        [786, 786, 786, 786, 786, 786, 786, 786],
        [786, 786, 786, 786, 786, 786, 786, 786],
        [786, 786, 786, 786, 786, 786, 786, 786]],

       [[786, 786, 786, 786, 786, 786, 786, 786],
        [786, 786, 786, 786, 786, 786, 786, 786],
        [786, 786, 786, 786, 786, 786, 786, 786],
        [786, 786, 786, 786, 786, 786, 786, 786]]])

In [59]:
np.full((3,2,4),3.14)

array([[[3.14, 3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14, 3.14]],

       [[3.14, 3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14, 3.14]],

       [[3.14, 3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14, 3.14]]])

In [60]:
# np.identity- a square matrix whose diagonal is 1

In [61]:
np.identity(5,dtype=int)
#np.eye(2,dtype=float)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [62]:
# arange and linspace
a=np.arange(0,201,20,dtype=int)
a

array([  0,  20,  40,  60,  80, 100, 120, 140, 160, 180, 200])

In [63]:
a=np.arange(20,-21,-4)
print(a)
a.sum()

[ 20  16  12   8   4   0  -4  -8 -12 -16 -20]


0

In [64]:
print(np.linspace(10,20,8,endpoint=False,dtype=int))
np.linspace(10,20,8,endpoint=False,dtype=float,retstep=True,)

[10 11 12 13 15 16 17 18]


(array([10.  , 11.25, 12.5 , 13.75, 15.  , 16.25, 17.5 , 18.75]), 1.25)

In [66]:
np.logspace(10,100,2,base=10)

array([1.e+010, 1.e+100])

In [67]:
np.geomspace(1,20,10)

array([ 1.        ,  1.39495079,  1.94588772,  2.71441762,  3.78647901,
        5.2819519 ,  7.368063  , 10.27808533, 14.33742329, 20.        ])

In [71]:
#array with tuple
b=np.array((23,45,78,98))
print(type(b))
b

<class 'numpy.ndarray'>


array([23, 45, 78, 98])

In [40]:
#  Array with a SET we can not created

In [72]:
a=np.array({1,2,3,4,5,6,7,8,9,1,1,1,1})
print(a)
print(a.ndim)
a.shape
type(a)


{1, 2, 3, 4, 5, 6, 7, 8, 9}
0


numpy.ndarray

In [73]:
c=np.array({1:23,2:46})
print(c.ndim)
# we cannot make array with dictionary and set objects...
#type(c)
c

0


array({1: 23, 2: 46}, dtype=object)

In [74]:
import numpy as np

# Second Class

In [75]:
# converting 1-D to 2-D and 3-D array

In [76]:
n1=np.arange(1,31)
n1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [79]:
np.reshape(n1,(5,6))
n1.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [80]:
n1.reshape(6,5,order='F') # 'C' for rows

array([[ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29],
       [ 6, 12, 18, 24, 30]])

In [82]:
a=n1.reshape(5,3,2,order='F')
a

array([[[ 1, 16],
        [ 6, 21],
        [11, 26]],

       [[ 2, 17],
        [ 7, 22],
        [12, 27]],

       [[ 3, 18],
        [ 8, 23],
        [13, 28]],

       [[ 4, 19],
        [ 9, 24],
        [14, 29]],

       [[ 5, 20],
        [10, 25],
        [15, 30]]])

In [49]:
a.dtype

dtype('int32')

In [50]:
np.reshape(n1,(1,3,10))

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]]])

In [51]:
# Converting 3-D to 2-D

In [84]:
mat=np.reshape(n1,(3,2,5),order='F')
mat

array([[[ 1,  7, 13, 19, 25],
        [ 4, 10, 16, 22, 28]],

       [[ 2,  8, 14, 20, 26],
        [ 5, 11, 17, 23, 29]],

       [[ 3,  9, 15, 21, 27],
        [ 6, 12, 18, 24, 30]]])

In [85]:
print(mat.shape)
mat.size

(3, 2, 5)


30

In [86]:
mat.reshape(5,6,order='F')

array([[ 1,  6, 11, 16, 21, 26],
       [ 2,  7, 12, 17, 22, 27],
       [ 3,  8, 13, 18, 23, 28],
       [ 4,  9, 14, 19, 24, 29],
       [ 5, 10, 15, 20, 25, 30]])

In [89]:
print(A)
Z=A
S=np.reshape(Z,(2,2,3))
print(S)
E=S.flatten()
print(type(E))
print(E)
E.ndim

[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>
[ 1  2  3  4  5  6  7  8  9 10 11 12]


1

In [91]:
print(mat)
mat.flatten()

[[[ 1  7 13 19 25]
  [ 4 10 16 22 28]]

 [[ 2  8 14 20 26]
  [ 5 11 17 23 29]]

 [[ 3  9 15 21 27]
  [ 6 12 18 24 30]]]


array([ 1,  7, 13, 19, 25,  4, 10, 16, 22, 28,  2,  8, 14, 20, 26,  5, 11,
       17, 23, 29,  3,  9, 15, 21, 27,  6, 12, 18, 24, 30])

In [99]:
S.flatten()
a=list(S.flatten())

print(type(a))
a

<class 'list'>


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [100]:
# Unique()


In [4]:
ar=np.random.randint(5,11,24)
ar

array([ 6,  8, 10,  5,  9,  5, 10,  8,  7,  9, 10,  5,  7,  7,  9,  5,  5,
        9,  5,  9, 10,  9,  5,  7])

In [8]:
ar=np.random.random(24)
ar

array([0.96877268, 0.76997555, 0.40532169, 0.86370163, 0.01082482,
       0.07078942, 0.29215329, 0.17792729, 0.14618763, 0.91335082,
       0.92379213, 0.47657596, 0.99788211, 0.69709875, 0.55820652,
       0.14449789, 0.00774152, 0.12247998, 0.90923659, 0.59290927,
       0.78991534, 0.85680863, 0.65120732, 0.64432172])

In [9]:
import random
list1 = [1, 2, 3, 4, 5, 6]
print(random.choices(list1,k=10))

[4, 3, 4, 2, 1, 1, 6, 6, 3, 3]


In [10]:
np.unique(ar)

array([0.00774152, 0.01082482, 0.07078942, 0.12247998, 0.14449789,
       0.14618763, 0.17792729, 0.29215329, 0.40532169, 0.47657596,
       0.55820652, 0.59290927, 0.64432172, 0.65120732, 0.69709875,
       0.76997555, 0.78991534, 0.85680863, 0.86370163, 0.90923659,
       0.91335082, 0.92379213, 0.96877268, 0.99788211])

In [11]:
# coverting array to list
import numpy as np

In [12]:
print(ar.tolist())
T=ar.reshape(3,4,2,order='F')
print(T)
T.tolist()

[0.968772677600897, 0.7699755510877013, 0.40532168860163553, 0.8637016305404274, 0.010824824615807915, 0.07078942306062141, 0.29215328693137665, 0.17792728652586065, 0.14618762886772152, 0.9133508193199347, 0.9237921272506664, 0.47657596254334367, 0.9978821129716431, 0.697098749488745, 0.5582065174256767, 0.14449788737285507, 0.007741520825808368, 0.12247998130883375, 0.9092365940140978, 0.592909270092326, 0.7899153428986204, 0.8568086310431775, 0.651207318785245, 0.6443217212034252]
[[[0.96877268 0.99788211]
  [0.86370163 0.14449789]
  [0.29215329 0.90923659]
  [0.91335082 0.85680863]]

 [[0.76997555 0.69709875]
  [0.01082482 0.00774152]
  [0.17792729 0.59290927]
  [0.92379213 0.65120732]]

 [[0.40532169 0.55820652]
  [0.07078942 0.12247998]
  [0.14618763 0.78991534]
  [0.47657596 0.64432172]]]


[[[0.968772677600897, 0.9978821129716431],
  [0.8637016305404274, 0.14449788737285507],
  [0.29215328693137665, 0.9092365940140978],
  [0.9133508193199347, 0.8568086310431775]],
 [[0.7699755510877013, 0.697098749488745],
  [0.010824824615807915, 0.007741520825808368],
  [0.17792728652586065, 0.592909270092326],
  [0.9237921272506664, 0.651207318785245]],
 [[0.40532168860163553, 0.5582065174256767],
  [0.07078942306062141, 0.12247998130883375],
  [0.14618762886772152, 0.7899153428986204],
  [0.47657596254334367, 0.6443217212034252]]]

In [13]:
a1=np.random.randint(10,100,7)
a2=np.random.randint(10,100,5)
a3=np.random.randint(10,100,5)

In [125]:
a1

array([18, 82, 48, 85, 89, 51, 76])

In [126]:
print(a2)
a3

[76 29 70 90 60]


array([44, 16, 16, 51, 46])

In [127]:
np.concatenate((a1,a2,a3),axis=0)

array([18, 82, 48, 85, 89, 51, 76, 76, 29, 70, 90, 60, 44, 16, 16, 51, 46])

In [128]:
mat1=np.random.randint(10,100,20).reshape(5,4)
mat1

array([[66, 88, 61, 90],
       [72, 85, 77, 49],
       [84, 10, 47, 80],
       [28, 69, 59, 94],
       [20, 41, 92, 22]])

In [129]:
mat2=np.random.randint(10,100,30).reshape(5,6)
mat2

array([[29, 21, 31, 65, 82, 29],
       [38, 17, 42, 89, 74, 95],
       [45, 56, 19, 83, 59, 47],
       [54, 75, 67, 33, 71, 72],
       [52, 72, 74, 78, 23, 32]])

In [131]:
np.concatenate((mat1,mat2),axis=1)
# axis=1 columnwise
# axis=0 rawwise

array([[66, 88, 61, 90, 29, 21, 31, 65, 82, 29],
       [72, 85, 77, 49, 38, 17, 42, 89, 74, 95],
       [84, 10, 47, 80, 45, 56, 19, 83, 59, 47],
       [28, 69, 59, 94, 54, 75, 67, 33, 71, 72],
       [20, 41, 92, 22, 52, 72, 74, 78, 23, 32]])

In [132]:
q1=np.random.randint(50,100,20).reshape(5,4)
print(q1)
print("\n\n")
q2=np.random.randint(0,50,24).reshape(6,4)
print(q2)
print("\n\n")

Q=np.concatenate((q1,q2),axis=0)
print(Q)

[[96 91 80 65]
 [50 54 77 95]
 [71 83 83 60]
 [51 57 53 93]
 [92 67 77 62]]



[[36 48 23 14]
 [10 47 43  9]
 [26 14 34 28]
 [16 13 37 10]
 [29 14 39 29]
 [16  3 35 26]]



[[96 91 80 65]
 [50 54 77 95]
 [71 83 83 60]
 [51 57 53 93]
 [92 67 77 62]
 [36 48 23 14]
 [10 47 43  9]
 [26 14 34 28]
 [16 13 37 10]
 [29 14 39 29]
 [16  3 35 26]]


In [133]:
Q.tolist()

[[96, 91, 80, 65],
 [50, 54, 77, 95],
 [71, 83, 83, 60],
 [51, 57, 53, 93],
 [92, 67, 77, 62],
 [36, 48, 23, 14],
 [10, 47, 43, 9],
 [26, 14, 34, 28],
 [16, 13, 37, 10],
 [29, 14, 39, 29],
 [16, 3, 35, 26]]

In [78]:
# Slicing in array

In [134]:
ar1=np.random.randint(10,100,30)

In [135]:
ar1

array([93, 71, 21, 23, 53, 12, 64, 76, 74, 92, 45, 80, 44, 12, 13, 51, 68,
       82, 54, 42, 42, 59, 82, 25, 29, 43, 27, 35, 76, 79])

In [136]:
ar1[3]

23

In [137]:
ar1[2]

21

In [138]:
ar1[-1]

79

In [139]:
ar1[-30]

93

In [140]:
ar1[2:9:2]

array([21, 53, 64, 74])

In [141]:
mat2

array([[29, 21, 31, 65, 82, 29],
       [38, 17, 42, 89, 74, 95],
       [45, 56, 19, 83, 59, 47],
       [54, 75, 67, 33, 71, 72],
       [52, 72, 74, 78, 23, 32]])

In [87]:
mat2[0]

array([90, 14, 36, 81, 13, 94])

In [142]:
mat2[:-2]

array([[29, 21, 31, 65, 82, 29],
       [38, 17, 42, 89, 74, 95],
       [45, 56, 19, 83, 59, 47]])

In [143]:
mat2[-2:]

array([[54, 75, 67, 33, 71, 72],
       [52, 72, 74, 78, 23, 32]])

In [144]:
mat2[:,1:2]

array([[21],
       [17],
       [56],
       [75],
       [72]])

In [145]:
mat2[:,-4:-2]

array([[31, 65],
       [42, 89],
       [19, 83],
       [67, 33],
       [74, 78]])

In [146]:
mat2[-2:,-2:]


array([[71, 72],
       [23, 32]])

In [147]:
mat2

array([[29, 21, 31, 65, 82, 29],
       [38, 17, 42, 89, 74, 95],
       [45, 56, 19, 83, 59, 47],
       [54, 75, 67, 33, 71, 72],
       [52, 72, 74, 78, 23, 32]])

In [150]:
mat2[:,::3]

array([[29, 65],
       [38, 89],
       [45, 83],
       [54, 33],
       [52, 78]])

In [151]:
mat2[::2,:]

array([[29, 21, 31, 65, 82, 29],
       [45, 56, 19, 83, 59, 47],
       [52, 72, 74, 78, 23, 32]])

In [152]:
mat2[::2,::3]

array([[29, 65],
       [45, 83],
       [52, 78]])

In [154]:
print(mat2[[0,-1,4,3],:])
mat2[[-2],[-2]]

[[29 21 31 65 82 29]
 [52 72 74 78 23 32]
 [52 72 74 78 23 32]
 [54 75 67 33 71 72]]


array([71])

In [153]:
mat2


array([[29, 21, 31, 65, 82, 29],
       [38, 17, 42, 89, 74, 95],
       [45, 56, 19, 83, 59, 47],
       [54, 75, 67, 33, 71, 72],
       [52, 72, 74, 78, 23, 32]])

In [155]:
import numpy as np
mat3=np.random.randint(10,100,40).reshape(2,4,5)
mat3

array([[[74, 63, 88, 58, 33],
        [89, 43, 41, 75, 14],
        [69, 44, 80, 15, 39],
        [14, 79, 76, 15, 24]],

       [[61, 87, 88, 56, 23],
        [56, 95, 25, 52, 56],
        [55, 96, 48, 46, 18],
        [73, 54, 87, 74, 89]]])

In [156]:
mat3[0]

array([[74, 63, 88, 58, 33],
       [89, 43, 41, 75, 14],
       [69, 44, 80, 15, 39],
       [14, 79, 76, 15, 24]])

In [157]:
mat3[1]

array([[61, 87, 88, 56, 23],
       [56, 95, 25, 52, 56],
       [55, 96, 48, 46, 18],
       [73, 54, 87, 74, 89]])

In [158]:
mat3[0,:,-2:]

array([[58, 33],
       [75, 14],
       [15, 39],
       [15, 24]])

In [159]:
mat3[1,:2,:]

array([[61, 87, 88, 56, 23],
       [56, 95, 25, 52, 56]])

In [160]:
mat3[:,:,-2:]

array([[[58, 33],
        [75, 14],
        [15, 39],
        [15, 24]],

       [[56, 23],
        [52, 56],
        [46, 18],
        [74, 89]]])

In [161]:
mat3[:,-2:,:]

array([[[69, 44, 80, 15, 39],
        [14, 79, 76, 15, 24]],

       [[55, 96, 48, 46, 18],
        [73, 54, 87, 74, 89]]])

In [162]:
mat3[:,-2:,-2:]

array([[[15, 39],
        [15, 24]],

       [[46, 18],
        [74, 89]]])

In [163]:
# vastack, hstack,columnstack

In [164]:
a1=np.random.randint(10,100,7)
a2=np.random.randint(10,100,7)
a3=np.random.randint(10,100,7)
a4=np.random.randint(10,100,7)
print(a1,a2,a3,a4)

[31 74 19 77 66 90 35] [44 97 47 44 48 55 44] [95 90 84 72 30 33 69] [15 64 80 76 43 36 14]


In [165]:
a=np.vstack((a1,a2,a3,a4))
print(a)
a.shape

[[31 74 19 77 66 90 35]
 [44 97 47 44 48 55 44]
 [95 90 84 72 30 33 69]
 [15 64 80 76 43 36 14]]


(4, 7)

In [166]:
a1

array([31, 74, 19, 77, 66, 90, 35])

In [167]:
b=np.hstack((a1,a2,a3,a4))
print(b)
b.shape

[31 74 19 77 66 90 35 44 97 47 44 48 55 44 95 90 84 72 30 33 69 15 64 80
 76 43 36 14]


(28,)

In [168]:
a=np.column_stack((a1,a2,a3,a4))
a

array([[31, 44, 95, 15],
       [74, 97, 90, 64],
       [19, 47, 84, 80],
       [77, 44, 72, 76],
       [66, 48, 30, 43],
       [90, 55, 33, 36],
       [35, 44, 69, 14]])

In [119]:
# intersect-1D and setdiff-1D

In [169]:
a1=np.random.randint(10,15,20)
a2=np.random.randint(13,20,20)

In [170]:
a1

array([12, 12, 14, 14, 13, 11, 12, 13, 14, 10, 11, 12, 11, 14, 12, 12, 14,
       12, 10, 11])

In [171]:
a2

array([13, 13, 13, 17, 16, 19, 15, 16, 16, 17, 14, 19, 18, 14, 14, 16, 13,
       18, 18, 15])

In [172]:
np.intersect1d(a1,a2)

array([13, 14])

In [173]:
np.unique(a1)

array([10, 11, 12, 13, 14])

In [174]:
np.unique(a2)

array([13, 14, 15, 16, 17, 18, 19])

In [175]:
np.setdiff1d(a1,a2)

array([10, 11, 12])

In [176]:
np.setdiff1d(a2,a1)

array([15, 16, 17, 18, 19])

 # Array arithmaric

In [128]:
a1+6

array([19, 16, 16, 17, 16, 16, 18, 20, 16, 20, 16, 16, 18, 16, 17, 19, 17,
       19, 19, 18])

In [177]:
print(a1+a2)
print(a1,a2)

[25 25 27 31 29 30 27 29 30 27 25 31 29 28 26 28 27 30 28 26]
[12 12 14 14 13 11 12 13 14 10 11 12 11 14 12 12 14 12 10 11] [13 13 13 17 16 19 15 16 16 17 14 19 18 14 14 16 13 18 18 15]


In [178]:
np.sum((a1,a2))

558

In [179]:
np.sum((a1,a2),axis=0)

array([25, 25, 27, 31, 29, 30, 27, 29, 30, 27, 25, 31, 29, 28, 26, 28, 27,
       30, 28, 26])

In [180]:
a1

array([12, 12, 14, 14, 13, 11, 12, 13, 14, 10, 11, 12, 11, 14, 12, 12, 14,
       12, 10, 11])

In [181]:
a2

array([13, 13, 13, 17, 16, 19, 15, 16, 16, 17, 14, 19, 18, 14, 14, 16, 13,
       18, 18, 15])

In [182]:
np.sum((a1,a2),axis=1)

array([244, 314])

In [183]:
a1-3

array([ 9,  9, 11, 11, 10,  8,  9, 10, 11,  7,  8,  9,  8, 11,  9,  9, 11,
        9,  7,  8])

In [184]:
a1-a2

array([-1, -1,  1, -3, -3, -8, -3, -3, -2, -7, -3, -7, -7,  0, -2, -4,  1,
       -6, -8, -4])

In [185]:
np.subtract(a1,a2)

array([-1, -1,  1, -3, -3, -8, -3, -3, -2, -7, -3, -7, -7,  0, -2, -4,  1,
       -6, -8, -4])

In [186]:
np.diff((a1,a2),axis=0) # a2-a1

array([[ 1,  1, -1,  3,  3,  8,  3,  3,  2,  7,  3,  7,  7,  0,  2,  4,
        -1,  6,  8,  4]])

In [187]:
np.diff((a1,a2),axis=1) # a2-a1

array([[ 0,  2,  0, -1, -2,  1,  1,  1, -4,  1,  1, -1,  3, -2,  0,  2,
        -2, -2,  1],
       [ 0,  0,  4, -1,  3, -4,  1,  0,  1, -3,  5, -1, -4,  0,  2, -3,
         5,  0, -3]])

In [188]:
# multiply

In [189]:
a1

array([12, 12, 14, 14, 13, 11, 12, 13, 14, 10, 11, 12, 11, 14, 12, 12, 14,
       12, 10, 11])

In [190]:
a2

array([13, 13, 13, 17, 16, 19, 15, 16, 16, 17, 14, 19, 18, 14, 14, 16, 13,
       18, 18, 15])

In [191]:
np.multiply(a1,a2)

array([156, 156, 182, 238, 208, 209, 180, 208, 224, 170, 154, 228, 198,
       196, 168, 192, 182, 216, 180, 165])

In [192]:
mat1=np.random.randint(1,10,20).reshape(5,4)
mat1


array([[8, 1, 8, 3],
       [3, 4, 3, 6],
       [7, 7, 1, 5],
       [7, 2, 6, 8],
       [2, 8, 5, 7]])

In [193]:
mat1+100

array([[108, 101, 108, 103],
       [103, 104, 103, 106],
       [107, 107, 101, 105],
       [107, 102, 106, 108],
       [102, 108, 105, 107]])

In [ ]:
mat2=np.random.randint(10,30,20).reshape(5,4)
mat2

In [146]:
np.multiply(mat1,mat2)

ValueError: operands could not be broadcast together with shapes (5,4) (5,6) 

In [ ]:
np.divide(mat1,mat2)

In [ ]:
mat2/2

In [ ]:
mat2//10

In [ ]:
np.power(mat2,2)

In [ ]:
# saving a numpy file

In [ ]:
np.save('matrix2',mat2) # extension .npy

In [ ]:
var1=np.save('matrix1',mat1)

In [ ]:
import os
os.getcwd()