In [1]:
import pandas as pd
import numpy as np

In [2]:
ar=np.array([23,42,15,67,73,51,82])

In [4]:
ar


array([23, 42, 15, 67, 73, 51, 82])

In [5]:
print(type(ar))

<class 'numpy.ndarray'>


In [6]:
# dataSeries-column of excel
# dataseries makes datafame

In [7]:
#pandas- panel data

In [9]:
ser1=pd.Series(ar,name='Kuldeep')

In [10]:
ser1


0    23
1    42
2    15
3    67
4    73
5    51
6    82
Name: Kuldeep, dtype: int32

In [11]:
type(ser1)

pandas.core.series.Series

In [12]:
a1=np.random.randint(1000000000000,7000000000000,10,dtype="int64")
a1

array([1779261116322, 4064575114857, 6409472742944, 3207348644319,
       5846226179248, 4026265446477, 6257671393878, 3537051675030,
       6364224311955, 4696645223108], dtype=int64)

In [13]:
pd.Series(np.random.randint(10,50,10),dtype=str,name='Kuldep')

0    43
1    40
2    10
3    16
4    23
5    10
6    28
7    32
8    47
9    27
Name: Kuldep, dtype: object

In [14]:
pd.Series(a1)

0    1779261116322
1    4064575114857
2    6409472742944
3    3207348644319
4    5846226179248
5    4026265446477
6    6257671393878
7    3537051675030
8    6364224311955
9    4696645223108
dtype: int64

In [16]:
ser2=pd.Series([34,98.9,87,'Hello',8+7j,True,(23,54,78,98.9)])
ser2

0                    34
1                  98.9
2                    87
3                 Hello
4                (8+7j)
5                  True
6    (23, 54, 78, 98.9)
dtype: object

In [17]:
ser2.explode()

0        34
1      98.9
2        87
3     Hello
4    (8+7j)
5      True
6        23
6        54
6        78
6      98.9
dtype: object

In [18]:
ser1

0    23
1    42
2    15
3    67
4    73
5    51
6    82
Name: Kuldeep, dtype: int32

In [19]:
ser1[2:6]

2    15
3    67
4    73
5    51
Name: Kuldeep, dtype: int32

In [20]:
ser=pd.Series([23,45,21,67,54,78],index=['a','b','c','d','e','f'],dtype=float)

In [21]:
ser

a    23.0
b    45.0
c    21.0
d    67.0
e    54.0
f    78.0
dtype: float64

In [22]:
myarr=np.random.randint(10,20,40).reshape(5,8)
print(myarr)
pd.Series(myarr)

[[18 14 10 18 18 12 12 12]
 [13 19 11 10 10 19 15 13]
 [15 12 13 10 18 19 18 16]
 [19 17 15 17 10 12 14 11]
 [10 17 10 15 14 18 11 13]]


ValueError: Data must be 1-dimensional

In [23]:
ser[-2]

54.0

In [24]:
ser['a':'e']

a    23.0
b    45.0
c    21.0
d    67.0
e    54.0
dtype: float64

In [26]:
ser[2:]

c    21.0
d    67.0
e    54.0
f    78.0
dtype: float64

In [27]:
# dictionary to series

In [30]:
d={'Hindi':89,'English':77,'Math':67,'Science':78}
ser2=pd.Series(d)

In [31]:
ser2

Hindi      89
English    77
Math       67
Science    78
dtype: int64

In [32]:
pd.Series((23,45,78,98,7,87,98,7))

0    23
1    45
2    78
3    98
4     7
5    87
6    98
7     7
dtype: int64

In [33]:
pd.Series({1,2,2,6,5,41,1,1}) # it will not work

TypeError: 'set' type is unordered

In [34]:
pd.Series('Hello')

0    Hello
dtype: object

In [35]:
print(ser1)

0    23
1    42
2    15
3    67
4    73
5    51
6    82
Name: Kuldeep, dtype: int32


In [36]:
ser1.dtype

dtype('int32')

In [37]:
ser1.size

7

In [38]:
s=pd.Series([34,67,None,45,81,None,33,None])

In [39]:
s

0    34.0
1    67.0
2     NaN
3    45.0
4    81.0
5     NaN
6    33.0
7     NaN
dtype: float64

In [46]:
s.isnull() # it will tell where we have null
#dropna()
#ffill()
# backfill()
s.fillna(s.mean())

0    34.0
1    67.0
2    52.0
3    45.0
4    81.0
5    52.0
6    33.0
7    52.0
dtype: float64

In [47]:
print(s.sum())
s

260.0


0    34.0
1    67.0
2     NaN
3    45.0
4    81.0
5     NaN
6    33.0
7     NaN
dtype: float64

In [48]:
s.isnull().sum() # to get the no of missing values in a series or dataframe

3

In [49]:
ser2

Hindi      89
English    77
Math       67
Science    78
dtype: int64

In [50]:
ser2['Math']=69

In [51]:
ser2.sum()

313

In [52]:
ser2+56 #/*-%//

Hindi      145
English    133
Math       125
Science    134
dtype: int64

In [53]:
ser1=ser1.add_prefix(prefix='No.')

In [54]:
ser1.add_suffix(suffix='pos')

No.0pos    23
No.1pos    42
No.2pos    15
No.3pos    67
No.4pos    73
No.5pos    51
No.6pos    82
Name: Kuldeep, dtype: int32

In [55]:
ser1

No.0    23
No.1    42
No.2    15
No.3    67
No.4    73
No.5    51
No.6    82
Name: Kuldeep, dtype: int32

In [58]:
#ser1.aggregate('mean')
a=ser1.aggregate(['min','max','sum'])
print(ser1.mean())
a

50.42857142857143


min     15
max     82
sum    353
Name: Kuldeep, dtype: int64

In [59]:
ser1.aggregate(['mean','median','max','min','sum','std'])

mean       50.428571
median     51.000000
max        82.000000
min        15.000000
sum       353.000000
std        25.363078
Name: Kuldeep, dtype: float64

In [60]:
ser1_1=pd.Series([23,45,78,98,45])

In [61]:
ser1_1

0    23
1    45
2    78
3    98
4    45
dtype: int64

In [62]:
ser1

No.0    23
No.1    42
No.2    15
No.3    67
No.4    73
No.5    51
No.6    82
Name: Kuldeep, dtype: int32

In [68]:
n_ser=pd.concat([ser1,ser1_1],ignore_index=True)
n_ser

0     23
1     42
2     15
3     67
4     73
5     51
6     82
7     23
8     45
9     78
10    98
11    45
dtype: int64

In [69]:
n_ser.argmax()

10

In [70]:
n_ser.argmin()

2

In [71]:
print(n_ser.argsort())
n_ser

0      2
1      0
2      7
3      1
4      8
5     11
6      5
7      3
8      4
9      9
10     6
11    10
dtype: int64


0     23
1     42
2     15
3     67
4     73
5     51
6     82
7     23
8     45
9     78
10    98
11    45
dtype: int64

In [72]:
s1=pd.Series(['Hello','My','Name','is','Ajay'])
s1

0    Hello
1       My
2     Name
3       is
4     Ajay
dtype: object

In [73]:
s1.explode()

0    Hello
1       My
2     Name
3       is
4     Ajay
dtype: object

In [74]:
s1.argsort()

0    4
1    0
2    1
3    2
4    3
dtype: int64

In [75]:
s.argmax()

4

In [76]:
s

0    34.0
1    67.0
2     NaN
3    45.0
4    81.0
5     NaN
6    33.0
7     NaN
dtype: float64

In [77]:
s.argsort() # IT  REMOVES NULL VALUES FIRST  THEN  GIVE SORT RESULT

0    4
1    0
2   -1
3    2
4    1
5   -1
6    3
7   -1
dtype: int64

In [78]:
s.dropna()

0    34.0
1    67.0
3    45.0
4    81.0
6    33.0
dtype: float64

In [79]:
ser

a    23.0
b    45.0
c    21.0
d    67.0
e    54.0
f    78.0
dtype: float64

In [80]:
ser.astype(float)

a    23.0
b    45.0
c    21.0
d    67.0
e    54.0
f    78.0
dtype: float64

In [81]:
s=pd.Series([34,67,None,45,81,None,33,None])
s

0    34.0
1    67.0
2     NaN
3    45.0
4    81.0
5     NaN
6    33.0
7     NaN
dtype: float64

In [82]:
s.fillna('Rana') #inplace =true to fill null value in orgininal dta


0    34.0
1    67.0
2    Rana
3    45.0
4    81.0
5    Rana
6    33.0
7    Rana
dtype: object

In [83]:
s.backfill() #fill forward will fill forward s.ffill()

0    34.0
1    67.0
2    45.0
3    45.0
4    81.0
5    33.0
6    33.0
7     NaN
dtype: float64

In [84]:
s.ffill()

0    34.0
1    67.0
2    67.0
3    45.0
4    81.0
5    81.0
6    33.0
7    33.0
dtype: float64

In [85]:
s1=pd.Series([31,21,56,42,21,56])

In [86]:
s1

0    31
1    21
2    56
3    42
4    21
5    56
dtype: int64

In [87]:
s1.drop_duplicates()

0    31
1    21
2    56
3    42
dtype: int64

In [88]:
s2=pd.Series([1,2,3,4,[44,55,66,[11,22,33,44],5,6,],98])

In [1]:
s2

NameError: name 's2' is not defined

In [90]:
s2.explode().explode()


0     1
1     2
2     3
3     4
4    44
4    55
4    66
4    11
4    22
4    33
4    44
4     5
4     6
5    98
dtype: object

In [91]:
s2[4]

[44, 55, 66, [11, 22, 33, 44], 5, 6]

# fourth lecture

In [92]:
ser=pd.Series(ar,index=['1','2','3','4','5','6','7'])
ser

1    23
2    42
3    15
4    67
5    73
6    51
7    82
dtype: int32

In [93]:
ser[-2]

51

# series arithmaic

In [97]:
ser+6+4

1    33
2    52
3    25
4    77
5    83
6    61
7    92
dtype: int32

In [98]:
ser.add(10)

1    33
2    52
3    25
4    77
5    83
6    61
7    92
dtype: int32

In [99]:
ser1=pd.Series([23,45,21,67,54])

In [100]:
ser=pd.Series(ar)
print(ser)
ser1

0    23
1    42
2    15
3    67
4    73
5    51
6    82
dtype: int32


0    23
1    45
2    21
3    67
4    54
dtype: int64

In [101]:
(ser+ser1)

0     46.0
1     87.0
2     36.0
3    134.0
4    127.0
5      NaN
6      NaN
dtype: float64

In [102]:
ser.add(ser1,fill_value=100)
# 23+NaN=Nan
# 23+0=23

0     46.0
1     87.0
2     36.0
3    134.0
4    127.0
5    151.0
6    182.0
dtype: float64

In [103]:
ser1-ser

0     0.0
1     3.0
2     6.0
3     0.0
4   -19.0
5     NaN
6     NaN
dtype: float64

In [104]:
ser.subtract(ser1,fill_value=100)

0     0.0
1    -3.0
2    -6.0
3     0.0
4    19.0
5   -49.0
6   -18.0
dtype: float64

In [105]:
print(ser)
ser/2

0    23
1    42
2    15
3    67
4    73
5    51
6    82
dtype: int32


0    11.5
1    21.0
2     7.5
3    33.5
4    36.5
5    25.5
6    41.0
dtype: float64

In [106]:
ser1//ser

0    1.0
1    1.0
2    1.0
3    1.0
4    0.0
5    NaN
6    NaN
dtype: float64

In [107]:
ser1.divide(ser,fill_value=0)

0    1.000000
1    1.071429
2    1.400000
3    1.000000
4    0.739726
5    0.000000
6    0.000000
dtype: float64

In [108]:
ser1*3

0     69
1    135
2     63
3    201
4    162
dtype: int64

In [109]:
ser*ser1

0     529.0
1    1890.0
2     315.0
3    4489.0
4    3942.0
5       NaN
6       NaN
dtype: float64

In [110]:
ser.multiply(ser1,fill_value=100)

0     529.0
1    1890.0
2     315.0
3    4489.0
4    3942.0
5    5100.0
6    8200.0
dtype: float64

In [111]:
ser.pow(4)

0      279841
1     3111696
2       50625
3    20151121
4    28398241
5     6765201
6    45212176
dtype: int32

In [112]:
ser.pow(ser1,fill_value=100)

0     2.088047e+31
1     1.112290e+73
2     4.987885e+24
3    2.223370e+122
4    4.163269e+100
5    5.715018e+170
6    2.406497e+191
dtype: float64

In [113]:
ser1%5

0    3
1    0
2    1
3    2
4    4
dtype: int64

In [114]:
ser%ser1

0     0.0
1    42.0
2    15.0
3     0.0
4    19.0
5     NaN
6     NaN
dtype: float64

In [115]:
ser.mean()

50.42857142857143

In [116]:
ser.median()

51.0

In [117]:
ser.mode()

0    15
1    23
2    42
3    51
4    67
5    73
6    82
dtype: int32

In [118]:
ser.std()

25.363077776281692

In [119]:
ser.var()
ser

0    23
1    42
2    15
3    67
4    73
5    51
6    82
dtype: int32

In [120]:
print(ser.quantile(0.75))
print(ser.quantile(0.5))
print(ser.quantile(1))
ser.info()
print(ser.describe())
((70-32.5)*1.5)+70# uppper quartile

70.0
51.0
82.0
<class 'pandas.core.series.Series'>
RangeIndex: 7 entries, 0 to 6
Series name: None
Non-Null Count  Dtype
--------------  -----
7 non-null      int32
dtypes: int32(1)
memory usage: 156.0 bytes
count     7.000000
mean     50.428571
std      25.363078
min      15.000000
25%      32.500000
50%      51.000000
75%      70.000000
max      82.000000
dtype: float64


126.25

In [121]:
ser.quantile(.99)

81.46

In [122]:
ser.skew()

-0.2600526731834873

In [123]:
ser.kurt()

-1.481171517949221

# DATA FRAME

In [124]:
# DATA FRAME from dictionary
import pandas as pd
import numpy as np

In [125]:
student={'Name':['Vijay','Suman','Ravi','Rahul','Priya'],
        'Marks':[78,82,None,None,65],
        'Age':[23,None,23,31,24],
         'Gender':['M','F','M',None,'F']}

In [126]:
student

{'Name': ['Vijay', 'Suman', 'Ravi', 'Rahul', 'Priya'],
 'Marks': [78, 82, None, None, 65],
 'Age': [23, None, 23, 31, 24],
 'Gender': ['M', 'F', 'M', None, 'F']}

In [127]:
df=pd.DataFrame(student)
df

Name  Marks   Age Gender
0  Vijay   78.0  23.0      M
1  Suman   82.0   NaN      F
2   Ravi    NaN  23.0      M
3  Rahul    NaN  31.0   None
4  Priya   65.0  24.0      F

In [128]:
df.isnull().sum()

Name      0
Marks     2
Age       1
Gender    1
dtype: int64

In [129]:
df.describe()

Marks       Age
count   3.000000   4.00000
mean   75.000000  25.25000
std     8.888194   3.86221
min    65.000000  23.00000
25%    71.500000  23.00000
50%    78.000000  23.50000
75%    80.000000  25.75000
max    82.000000  31.00000

In [130]:
df.shape

(5, 4)

In [131]:
df.size

20

In [132]:
df

Name  Marks   Age Gender
0  Vijay   78.0  23.0      M
1  Suman   82.0   NaN      F
2   Ravi    NaN  23.0      M
3  Rahul    NaN  31.0   None
4  Priya   65.0  24.0      F

In [133]:
df.columns=['Name','Percent','Age','M/F']
df

Name  Percent   Age   M/F
0  Vijay     78.0  23.0     M
1  Suman     82.0   NaN     F
2   Ravi      NaN  23.0     M
3  Rahul      NaN  31.0  None
4  Priya     65.0  24.0     F

In [134]:
df.rename(columns={'Name':'First_name','Umar':'age'},inplace=True)

In [135]:
df

First_name  Percent   Age   M/F
0      Vijay     78.0  23.0     M
1      Suman     82.0   NaN     F
2       Ravi      NaN  23.0     M
3      Rahul      NaN  31.0  None
4      Priya     65.0  24.0     F

In [140]:
df.drop(columns=['M/F'])
#df.drop(['M/F'],axis=1)

First_name  Percent   Age
0      Vijay     78.0  23.0
1      Suman     82.0   NaN
2       Ravi      NaN  23.0
3      Rahul      NaN  31.0
4      Priya     65.0  24.0

In [137]:
df.drop(index=[1,3])

First_name  Percent   Age M/F
0      Vijay     78.0  23.0   M
2       Ravi      NaN  23.0   M
4      Priya     65.0  24.0   F

In [138]:
df1=pd.DataFrame(student,index=['a','b','c','d','e'])

In [141]:
df1

Name  Marks   Age Gender
a  Vijay   78.0  23.0      M
b  Suman   82.0   NaN      F
c   Ravi    NaN  23.0      M
d  Rahul    NaN  31.0   None
e  Priya   65.0  24.0      F

In [142]:
df

First_name  Percent   Age   M/F
0      Vijay     78.0  23.0     M
1      Suman     82.0   NaN     F
2       Ravi      NaN  23.0     M
3      Rahul      NaN  31.0  None
4      Priya     65.0  24.0     F

In [143]:
df['M/F']
#df.M/F

0       M
1       F
2       M
3    None
4       F
Name: M/F, dtype: object

In [144]:
type(df['Percent'])

pandas.core.series.Series

In [148]:
df['Percent'].dtype

dtype('float64')

In [150]:
a=df['Percent']
a

0    78.0
1    82.0
2     NaN
3     NaN
4    65.0
Name: Percent, dtype: float64

In [151]:
type(df)

pandas.core.frame.DataFrame

In [152]:
df.columns

Index(['First_name', 'Percent', 'Age', 'M/F'], dtype='object')

In [153]:
df1.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [154]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [155]:
df1.columns

Index(['Name', 'Marks', 'Age', 'Gender'], dtype='object')

In [156]:
df

First_name  Percent   Age   M/F
0      Vijay     78.0  23.0     M
1      Suman     82.0   NaN     F
2       Ravi      NaN  23.0     M
3      Rahul      NaN  31.0  None
4      Priya     65.0  24.0     F

In [157]:
df.isnull().sum()

First_name    0
Percent       2
Age           1
M/F           1
dtype: int64

In [158]:
df[df['Percent'].isnull()]

First_name  Percent   Age   M/F
2       Ravi      NaN  23.0     M
3      Rahul      NaN  31.0  None

In [159]:
df[df['Percent']>75]

First_name  Percent   Age M/F
0      Vijay     78.0  23.0   M
1      Suman     82.0   NaN   F

In [160]:
df[(df['Percent']>75)&(df['M/F']=='M')]

First_name  Percent   Age M/F
0      Vijay     78.0  23.0   M

In [162]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   First_name  5 non-null      object 
 1   Percent     3 non-null      float64
 2   Age         4 non-null      float64
 3   M/F         4 non-null      object 
dtypes: float64(2), object(2)
memory usage: 288.0+ bytes


In [163]:
df.describe().T

count   mean       std   min   25%   50%    75%   max
Percent    3.0  75.00  8.888194  65.0  71.5  78.0  80.00  82.0
Age        4.0  25.25  3.862210  23.0  23.0  23.5  25.75  31.0

In [164]:
df.describe(include=object).T

count unique    top freq
First_name     5      5  Vijay    1
M/F            4      2      M    2

In [165]:
df.describe(include='all')

First_name    Percent       Age  M/F
count           5   3.000000   4.00000    4
unique          5        NaN       NaN    2
top         Vijay        NaN       NaN    M
freq            1        NaN       NaN    2
mean          NaN  75.000000  25.25000  NaN
std           NaN   8.888194   3.86221  NaN
min           NaN  65.000000  23.00000  NaN
25%           NaN  71.500000  23.00000  NaN
50%           NaN  78.000000  23.50000  NaN
75%           NaN  80.000000  25.75000  NaN
max           NaN  82.000000  31.00000  NaN

In [167]:
df.corr()

Percent  Age
Percent      1.0 -1.0
Age         -1.0  1.0

In [168]:
df.cov()

Percent        Age
Percent     79.0  -6.500000
Age         -6.5  14.916667

In [169]:
# List to DATA FRAME

In [170]:
lis=[[1011,'Rajesh',25,'G',34000],
    [1012,'Suresh',25,'PG',48000],
     [1013,'Geeta',24,'G',30000],
     [1014,'Mukesh',27,'G',40000]]

In [171]:
df2=pd.DataFrame(lis,columns=['Emp_id','Emp_Name','Emp_age','Qualification','Salary'])

In [172]:
df2

Emp_id Emp_Name  Emp_age Qualification  Salary
0    1011   Rajesh       25             G   34000
1    1012   Suresh       25            PG   48000
2    1013    Geeta       24             G   30000
3    1014   Mukesh       27             G   40000

In [173]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   Emp_id         4 non-null      int64 
 1   Emp_Name       4 non-null      object
 2   Emp_age        4 non-null      int64 
 3   Qualification  4 non-null      object
 4   Salary         4 non-null      int64 
dtypes: int64(3), object(2)
memory usage: 288.0+ bytes


In [174]:
df2.describe(include='all').T

count unique     top freq     mean          std      min  \
Emp_id          4.0    NaN     NaN  NaN   1012.5     1.290994   1011.0   
Emp_Name          4      4  Rajesh    1      NaN          NaN      NaN   
Emp_age         4.0    NaN     NaN  NaN    25.25     1.258306     24.0   
Qualification     4      2       G    3      NaN          NaN      NaN   
Salary          4.0    NaN     NaN  NaN  38000.0  7831.560083  30000.0   

                   25%      50%      75%      max  
Emp_id         1011.75   1012.5  1013.25   1014.0  
Emp_Name           NaN      NaN      NaN      NaN  
Emp_age          24.75     25.0     25.5     27.0  
Qualification      NaN      NaN      NaN      NaN  
Salary         33000.0  37000.0  42000.0  48000.0

In [175]:
df2.corr()

Emp_id   Emp_age        Salary
Emp_id   1.000000e+00  0.512989 -1.199406e-16
Emp_age  5.129892e-01  1.000000  4.059061e-01
Salary  -1.199406e-16  0.405906  1.000000e+00

In [176]:
df2.cov()

Emp_id      Emp_age        Salary
Emp_id   1.666667     0.833333  0.000000e+00
Emp_age  0.833333     1.583333  4.000000e+03
Salary   0.000000  4000.000000  6.133333e+07

In [ ]:
# Series to Dataframe

In [177]:
import pandas as pd
import numpy as np
ser1=pd.Series(np.random.randint(18,35,30))
ser1.T

0     29
1     28
2     29
3     29
4     32
5     23
6     22
7     20
8     27
9     22
10    28
11    31
12    29
13    22
14    28
15    30
16    31
17    25
18    29
19    32
20    34
21    19
22    31
23    28
24    29
25    27
26    29
27    31
28    29
29    26
dtype: int32

In [178]:
ser2=pd.Series(np.random.randint(18000,75000,30))

In [179]:
df3=pd.DataFrame({'Age':ser1,'Salary':ser2})

In [180]:
df3

Age  Salary
0    29   69366
1    28   61806
2    29   27931
3    29   52506
4    32   68745
5    23   23213
6    22   38852
7    20   59345
8    27   54531
9    22   66291
10   28   29735
11   31   22916
12   29   41725
13   22   46833
14   28   50349
15   30   54593
16   31   57613
17   25   22514
18   29   43763
19   32   35759
20   34   56131
21   19   61036
22   31   33834
23   28   53432
24   29   34673
25   27   54212
26   29   71769
27   31   58155
28   29   23565
29   26   68791

In [186]:
print(df3[df3['Salary']==min(df3['Salary'])])
#df3['Salary'][df3['Salary']>=50000].sum()
df3[df3['Salary']>=50000].sum()

    Age  Salary
17   25   22514


Age           470
Salary    1018671
dtype: int64

In [ ]:
# age>30 and Slary>50000

In [187]:
df3['Age'][(df3['Age']>30)&(df3['Salary']>50000)].mean()

32.0

In [188]:
df

First_name  Percent   Age   M/F
0      Vijay     78.0  23.0     M
1      Suman     82.0   NaN     F
2       Ravi      NaN  23.0     M
3      Rahul      NaN  31.0  None
4      Priya     65.0  24.0     F

In [189]:
df1

Name  Marks   Age Gender
a  Vijay   78.0  23.0      M
b  Suman   82.0   NaN      F
c   Ravi    NaN  23.0      M
d  Rahul    NaN  31.0   None
e  Priya   65.0  24.0      F

In [190]:
df2


Emp_id Emp_Name  Emp_age Qualification  Salary
0    1011   Rajesh       25             G   34000
1    1012   Suresh       25            PG   48000
2    1013    Geeta       24             G   30000
3    1014   Mukesh       27             G   40000

In [194]:
# loc()-location
#iloc()-index location
df2.loc[0:3,('Emp_Name','Qualification')]


Emp_Name Qualification
0   Rajesh             G
1   Suresh            PG
2    Geeta             G
3   Mukesh             G

In [195]:
df2.loc[0:2,['Emp_Name','Emp_age','Salary']]

Emp_Name  Emp_age  Salary
0   Rajesh       25   34000
1   Suresh       25   48000
2    Geeta       24   30000

In [196]:

df2.iloc[0:2,1:3]

Emp_Name  Emp_age
0   Rajesh       25
1   Suresh       25

In [197]:
df2.iloc[[2,1],[1,4]]

Emp_Name  Salary
2    Geeta   30000
1   Suresh   48000

In [198]:
# value_counts, sort_values and group_by

In [199]:
df2.value_counts()

Emp_id  Emp_Name  Emp_age  Qualification  Salary
1011    Rajesh    25       G              34000     1
1012    Suresh    25       PG             48000     1
1013    Geeta     24       G              30000     1
1014    Mukesh    27       G              40000     1
dtype: int64

In [38]:
df2['Qualification'].value_counts()

G     3
PG    1
Name: Qualification, dtype: int64

In [39]:
df2.sort_values(by='Emp_Name')

Emp_id Emp_Name  Emp_age Qualification  Salary
2    1013    Geeta       24             G   30000
3    1014   Mukesh       27             G   40000
0    1011   Rajesh       25             G   34000
1    1012   Suresh       25            PG   48000

In [40]:
df2.sort_values(by='Salary',ascending=False)

Emp_id Emp_Name  Emp_age Qualification  Salary
1    1012   Suresh       25            PG   48000
3    1014   Mukesh       27             G   40000
0    1011   Rajesh       25             G   34000
2    1013    Geeta       24             G   30000

In [41]:
df2.sort_values(by='Emp_Name')

Emp_id Emp_Name  Emp_age Qualification  Salary
2    1013    Geeta       24             G   30000
3    1014   Mukesh       27             G   40000
0    1011   Rajesh       25             G   34000
1    1012   Suresh       25            PG   48000

In [42]:
df2['Emp_age'].sort_values()

2    24
0    25
1    25
3    27
Name: Emp_age, dtype: int64

In [202]:
df2.groupby(by='Qualification')[['Salary','Emp_age']].mean()

Salary    Emp_age
Qualification                         
G              34666.666667  25.333333
PG             48000.000000  25.000000

In [203]:
df2.groupby(by='Qualification')['Salary'].min()

Qualification
G     30000
PG    48000
Name: Salary, dtype: int64

In [204]:
df

First_name  Percent   Age   M/F
0      Vijay     78.0  23.0     M
1      Suman     82.0   NaN     F
2       Ravi      NaN  23.0     M
3      Rahul      NaN  31.0  None
4      Priya     65.0  24.0     F

In [205]:
df.groupby(by='M/F')['Percent'].mean()

M/F
F    73.5
M    78.0
Name: Percent, dtype: float64

In [ ]:
df

In [ ]:
df.fillna(df['M/F'].mode(),inplace=True)
df

In [ ]:
df['M/F'].fillna('M',inplace=True)

In [ ]:
df['age'].mode()

In [ ]:
df['Percent'].fillna((df['Percent']).mean(),inplace=True)

In [ ]:
df

In [ ]:
df['age'].fillna((df['age']).mean(),inplace=True)

In [ ]:
df

In [ ]:
# .apply() -- it is used to apply a function to a column in a dataframe

In [ ]:
df2

In [ ]:
def revise_salary(Salary):
    if Salary>40000:
        return Salary*1.05
    else:
        return Salary*1.1

In [ ]:
df2['Rev_salary']=df2['Salary'].apply(revise_salary)

# way of creating a new column

In [ ]:
df2

In [ ]:
df3

In [ ]:
del_ind=df3[(df3['Age']<25)&(df3['Salary']>50000)].index

In [ ]:
df25

In [ ]:
df3.drop(index=del_ind,inplace=True)

In [ ]:
df3